const authenticationConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  LOGOUT: 'USERS_LOGOUT',
  GOOGLE_LOGIN_REQUEST: 'USERS_GOOGLE_LOGIN_REQUEST',
  GOOGLE_LOGIN_SUCCESS: 'USERS_GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_FAILURE: 'USERS_GOOGLE_LOGIN_FAILURE',
};

export default authenticationConstants;
