const Images = {
    cityBackground: require("../images/DSC_0321.jpg"),
    familyShareLogo: require("../images/families_share_logo.png"),
    challengeImage:require( "../images/DSC_0321.jpg"),
    europeanUnionLogo: require("../images/european_union_logo.png"),
    kids: require("../images/kids.png"),
    noMatchImage: require("../images/404.png"),
    languages:{
    el: require("../images/el.png"),
    en: require("../images/en.png"),
		de: require("../images/de.png"),
    nl: require("../images/nl.png"),
    it: require("../images/it.png"),
    },
    gender: require("../images/gender.png"),
    couple: require("../images/couple.png"),
    coupleRed: require("../images/couple-red.png"),
    coupleGreen: require("../images/couple-green.png"),
    babyFace: require("../images/baby-face.png"),
    babyFaceRed: require("../images/baby-face-red.png"),
    babyFaceGreen: require("../images/baby-face-green.png"),
    babyFaceWhite :require( "../images/baby-face-white.png"),
    coupleWhite : require("../images/couple-white.png"),
    spinner: require("../images/loading-spinner.gif"),
    policy: require("../images/privacy-policy.png"),
		policyAccepted: require("../images/privacy-policy-accepted.png"),
		infoCircleRegular: require('../images/info-circle-regular.png'),
		userFriendsRegular: require('../images/user-friends-regular.png')
};
export default Images;
