const landingImage = {
  Cokido: require("../images/cokidoImage.png"),
  Venice: require("../images/veniceImage.png"),
  Budapest: require("../images/budapestImage.png"),
  Bologna: require("../images/bolognaImage.png"),
  all: require("../images/cokidoImage.png"),
  FBK: require("../images/fbkImage.png"),
  Thessaloniki: require("../images/thessalonikiImage.png"),
  Hamburg: require("../images/hamburgImage.png"),
  Pescara: require("../images/pescaraImage.png"),
  Rome: require("../images/romeImage.png"),
  Foscari: require("../images/foscariImage.png"),
  Ferrara: require("../images/ferraraImage.png"),
  Development: require("../images/developmentImage.png"),
  Parma: require("../images/parmaImage.png"),
  Nina: require("../images/ninaImage.png"),
  Padova: require("../images/padovaImage.png"),
  Verona: require("../images/veronaImage.png"),
  Martellago: require("../images/martellagoImage.png"),
  Andria: require("../images/andriaImage.png"),
  Homeschooling: require("../images/homeschoolingImage.png"),
  Pederobba: require("../images/pederobbaImage.png")
};

const Images = {
  citylabImage: landingImage[process.env.REACT_APP_CITYLAB],
  familyShareLogo: require("../images/families_share_logo.png"),
  challengeImage: require("../images/DSC_0321.jpg"),
  europeanUnionLogo: require("../images/european_union_logo.png"),
  kids: require("../images/kids.png"),
  noMatchImage: require("../images/404.png"),
  languages: {
    el: require("../images/el.png"),
    en: require("../images/en.png"),
    de: require("../images/de.png"),
    nl: require("../images/nl.png"),
    it: require("../images/it.png"),
    hu: require("../images/hu.png"),
    fr: require("../images/fr.png"),
  },
  gender: require("../images/gender.png"),
  couple: require("../images/couple.png"),
  coupleRed: require("../images/couple-red.png"),
  coupleGreen: require("../images/couple-green.png"),
  babyFace: require("../images/baby-face.png"),
  babyFaceRed: require("../images/baby-face-red.png"),
  babyFaceGreen: require("../images/baby-face-green.png"),
  babyFaceWhite: require("../images/baby-face-white.png"),
  coupleWhite: require("../images/couple-white.png"),
  spinner: require("../images/loading-spinner.gif"),
  policy: require("../images/privacy-policy.png"),
  policyAccepted: require("../images/privacy-policy-accepted.png"),
  infoCircleRegular: require("../images/info-circle-regular.png"),
  userFriendsRegular: require("../images/user-friends-regular.png"),
  mapMarkerAltRegular: require("../images/mapMarkerAltRegular.png"),
  thumbtackRegular: require("../images/thumbtackRegular.png"),
  euroSignRegular: require("../images/euroSignRegular.png"),
  promptImage: require("../images/promptImage.png")
};
export default Images;
